# Site settings
title: les beaux mots
email: hi@sarahsemark.com
description: "An experiment in lettering and language"
baseurl: "/les-beaux-mots"
url: "http://triggersandsparks.com"
twitter_username: sarahsemark
github_username:  sarahsemark

# Build settings
markdown: kramdown
permalink: pretty
